config/routes.rb
Rails.application.routes.draw do
  get 'functions/index'
  resources :cities, only: [:index, :show] do
    collection do
      get :fetch_temperatures, to: 'cities#fetch_temperatures'
    end
  end
  root to: 'cities#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  has_many :postulations
  belongs_to :company
end

app/models/city.rb
class City < ApplicationRecord
  has_many :weathers

  def last_temperature
    weathers.order(id: :desc).pluck(:temp).first
  end
end

app/models/company.rb
class Company < ApplicationRecord
  TYPES = ["private", "public"]
  has_many :benefits
  validates :company_type, inclusion: { in: TYPES }
end

app/models/postulation.rb
class Postulation < ApplicationRecord
  belongs_to :benefit
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :postulations
  
  def self.with_short_benefits
    joins(postulations: [benefit: :company])
      .where('benefits.amount < ?', 10_000_000)
      .where('companies.company_type = ?', "private")
  end
end

app/models/weather.rb
class Weather < ApplicationRecord
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: :show

  def index
    @cities = City.all.includes(:weathers)
  end

  def show; end

  def fetch_temperatures
    City.all.each do |city|
      temperatures = FetchTemperatureService.perform(city.name)
      temperatures&.each do |temperature|
        weather = Weather.find_or_initialize_by(time: temperature['dt'], city: city)
        weather.temp = temperature['main']['temp']
        weather.save
      end
    end
    redirect_to cities_path
  end

  private

    def set_city
      @city = City.find(params[:id])
    end
end

app/controllers/functions_controller.rb
class FunctionsController < ApplicationController
  def index
    users = [
      {name: "Juan", country: "Chile", age: 30},
      {name: "Pedro", country: "Argentina", age: 15},
      {name: "Manuel", country: "Perú", age: 26},
      {name: "Jose", country: "Ecuador", age: 22}
    ]
    @ordered_users = ordered_by_country(users)
    @youngest_user = youngest_user(users)
  end

  private

    def ordered_by_country(users)
      users.sort_by { |person| person[:country] }
    end

    def youngest_user(users)
      users.sort_by{ |person| person[:age] }.first[:name]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/functions_helper.rb
module FunctionsHelper
end

app/views/cities/index.html.erb
<section class="section">
  <h1 class="title is-1">Ciudades</h1>
  <hr>
  <%= link_to "Obtener últimas temperaturas", fetch_temperatures_cities_path, class: 'button' %>
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Temperatura</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @cities.each do |city| %>
        <tr>
          <td><%= city.name %></td>
          <td><%= city.last_temperature || 'No se encuentran datos cargados.' %></td>
          <td><%= link_to "Ver mas", city, class: 'button' %></td>
      <% end %>
    </tbody>
  </table>
</section>

app/views/cities/show.html.erb
<section class="section">
  <h1 class="title is-1"><%= @city.name %> | <%= @city.country_code %></h1>

  <h2 class="subtitle">Temperaturas</h2>
  <hr>
    <table class="table">
    <thead>
      <tr>
        <th>Temperatura</th>
        <th>Fecha de consulta</th>
      </tr>
    </thead>
    <tbody>
      <% @city.weathers.each do |weather| %>
        <tr>
          <td><%= weather.temp %></td>
          <td><%= Time.at(weather.time) %></td>
      <% end %>
    </tbody>
  </table>
</section>

app/views/functions/index.html.erb
<h1>Funciones aplicadas al hash de usuarios</h1>
<p>Usuarios ordenados por país: <%= @ordered_users %></p>
<p>Usuario más joven: <%= @youngest_user %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test4Talent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>